
# names of the rooms used for the widgets
rooms: ["A7001","A7002","A7006"]

#----------------------------------------------------------------------------------------------------------------------#
#                                         Config for Info Room widgets                                                 #
#----------------------------------------------------------------------------------------------------------------------#

createInfoRoomWidgets: True # True if room widgets should be created, False if not


roomWidgets:
  # prefix to the name of the widget
  widgetName: "Kontor A-%roomName%"

  # True if widget name should be added unchanged to the widget. I.e. "Kontor A-A2001" with current settings
  # False if room prefix should be deleted from the widget name. I.e. "Kontor A-2001" with current settings
  addPrefixToWidgetName: False

  # prefix for name of the widget in files on LM
  widgetNameInFiles: "Rom A-%roomName%"

  # True if prefix should be added to the widget name in files on LM, False if not
  addPrefixToWidgetNameInFiles: False

  # name of the schematic to use for the trend widget
  # if there is just one schematic inside the folder, then you can leave this empty
  schematicToUse:

  # names of the objects in the database that are needed for the widget
  objectsNamesWidget: ["Driftsmodus - Rom", "Tilstedesensor -", "Romtemperatur - Verdi",
                       "Romtemperatur - Aktivt settpunkt",
                       "Romtemperatur - Lokal", "Romtemperatur - Settpunkt", "Varmeaktuator - Tilbakemelding",
                       "Kjoleaktuator - Tilbakemelding", "CO2 i rom - Verdi", "Fukt i rom - Verdi"]


#----------------------------------------------------------------------------------------------------------------------#
#                                        Config for Trend widgets                                                      #
#----------------------------------------------------------------------------------------------------------------------#

createTrendWidgets: True # True if trend widgets should be created, False if not


trendWidgets:
  # prefix for name of the widget in files on LM
  widgetNameInFiles: "Trend A-%roomName%"

  # The prefix is A if the room name is A2002 inside array rooms
  # If true and the room name is A2002 then placeholder %romName% will be replaced with A2002
  # If false and the room name is A2002 then placeholder %romName% will be replaced with 2002
  addPrefixToWidgetName: False

  # name of the schematic to use for the trend widget
  # if there is just one schematic inside the folder, then you can leave this empty
  schematicToUse: ""

  # names of the objects in the database that are needed for the trend widget
  objectsNamesWidget: ["Romtemperatur - Verdi", "Romtemperatur - Aktivt settpunkt", "CO2 i rom - Verdi",
                "Tilstedesensor -"]


#----------------------------------------------------------------------------------------------------------------------#
#                                       Config for Levels and frameworks                                               #
#----------------------------------------------------------------------------------------------------------------------#

# True if mainStructure should be created, False if not
createStructures: false

structure:
  # if there is just one schematic inside the folder, then you can leave this empty
  # name of the schematic to use for the trend widget
  schematicLevel: "Vis-Romvisualisering_6_etg-Bygg_A_GTW-2023.11.24-08.33.yml"

  schematicFramework: "Vis-Rammeverk_romstyring_6_etg-Bygg_A_GTW-2023.11.24-08.33.yml"

  boxData:
    standard:
      template: "A6001"
      objectsNames: ["Romtemperatur - Verdi", "Varmeaktuator - Tilbakemelding",
                            "Kjoleaktuator - Tilbakemelding", "CO2 i rom - Verdi", "Tilstedesensor -"]

      normal: "Boksmidten.png"

      trendIcon: "trend_ikon.png"

    lying:
      template: "A6014"
      objectsNames: ["Romtemperatur - Verdi", "Varmeaktuator - Tilbakemelding",
                            "Kjoleaktuator - Tilbakemelding", "CO2 i rom - Verdi", "Tilstedesensor -"]

      normal: "boks_rom_liggende.png"

      trendIcon: "trend_ikon.png"

  # names of roms and corresponding names of the objects in the database that are needed for the level widget
  roomNames:
    standard:
      A6001: A6001
      A6002: A6002
      A6003: A6003
      A6004: A6004
      A6006: A6006
      A6007: A6007
      A6008: A6008
      A6009: A6009
      A6011: A6011
      A6012: A6012
      A6013: A6013
    lying:
      A6014: A6014
      A6015: A6015
      A6016: A6016
      A6017: A6017


